#!/usr/bin/env tsx
/**
 * Reads Foundry compilation artifacts and regenerates lib/abis.ts.
 * Run after `forge build`:  pnpm gen-abis
 */
import fs from 'fs'
import path from 'path'

const CONTRACTS_OUT = path.join(__dirname, '..', 'contracts', 'out')
const OUT_FILE      = path.join(__dirname, '..', 'lib', 'abis.ts')

function loadAbi(contractName: string): unknown {
  const p = path.join(CONTRACTS_OUT, `${contractName}.sol`, `${contractName}.json`)
  if (!fs.existsSync(p)) {
    throw new Error(`Artifact not found at ${p}. Run 'forge build' first.`)
  }
  return JSON.parse(fs.readFileSync(p, 'utf-8')).abi
}

const intentEscrowAbi = loadAbi('IntentEscrow')
const mockUsdcAbi     = loadAbi('MockUSDC')

const content = `// AUTO-GENERATED by scripts/gen-abis.ts — do not edit manually.
// Regenerate with: pnpm gen-abis  (requires: forge build)

export const INTENT_ESCROW_ABI = ${JSON.stringify(intentEscrowAbi, null, 2)} as const

export const MOCK_USDC_ABI = ${JSON.stringify(mockUsdcAbi, null, 2)} as const
`

fs.writeFileSync(OUT_FILE, content)
console.log('Generated lib/abis.ts from Foundry artifacts.')
